export const DEFAULT_SUPPLIERS: string[] = [
    "Coca-Cola",
    "Pepsi",
    "Efes Pilsen",
    "Tuborg",
    "Carlsberg",
    "Anadolu Efes",
    "Ülker",
    "Eti",
    "Torku",
    "Haribo",
    "Mars",
    "Nestle",
    "Unilever",
    "P&G",
    "Philip Morris",
    "JTI (Japan Tobacco)",
    "BAT (British American Tobacco)",
    "Red Bull",
    "Monster Energy",
    "Frito-Lay",
    "Metro Toptancı",
    "BİM Toptancı",
    "A101 Toptancı",
    "Diğer",
];
